'\" t
.\"
.\" Author: Vitaly Lipatov
.\"
.\" This file has been put into the public domain.
.\" You can do whatever you want with this file.
.\"
.TH ETERBACKUP "August 2015" "Version 0.5"

.SH NAME
eterpack \- packing directory tree to one archive file with journaling archiver zpaq.
.SH SYNOPSIS
.B eterpack
.RI [command]
.RI [options]
.RI [path,]
.RI [path...]
.PP
.br
.SH DESCRIPTION
.BI
eterpack update scan every directory in the directory and create a archive file in target directory.
The goal is reduce the number of files from many thousands to a few.
Using journaling archiver zpaq we generate multi file archive (a file per every backup session).

.SH COMMANDS
.TP
.B update FROM TO
Makes backup all files in FROM to TO dir
.TP
.B restore BACKUP TO
Restore all backup files from BACKUP to TO dir
.TP
.B test BACKUP
Check backup integrity
.TP
.B compare "BACKUP" "TO"
Compare backup BACKUP with local files in TO dir

.SH OPTIONS
.TP
.B -h
Display help
.TP
.B -V
Show version and exit
.TP
.B --depth "N"
set depth for subdirs (update only)
.TP
.B --exclude "name"
exclude dir 'name' from packing
.TP
.B --execute "command"
execute 'command' after every archive
.TP
.B --checksum
force checking file contains, not date only

.SH EXAMPLES
.TP
.B
# eterpack update /var/log/ /tmp/backup
.TP
.B
# eterpack extract /tmp/backup /tmp/someplace
.TP
.B
# eterpack compare /tmp/backup /tmp/someplace
.TP
.B
# eterpack test /tmp/backup
.TP
.B
# eterpack update --execute "echo" /var/log/ /tmp/backup
execute command echo tarball_name after every zpaq archive complete
.TP
.B
# eterpack update --depth 2 --exclude subdir /var/log/ /tmp/backup
pack dir1/subdir1, dir2/subdir2, exclude */subdir
.TP
.B
# eterpack update --depth 2 --exclude /dir/subdir /var/log/ /tmp/backup
pack dir1/subdir1, dir2/subdir2, exclude /dir/subdir

.SH BUGS
Please report any bugs to lav@etersoft.ru
.SH EXIT STATUS
.B eterpack
will return zero on success and non zero on operation failure.
.SH SEE ALSO
.BR erc (1), etertimemachine (1), zpaq (1), eterremove (1)
.TP
.B http://wiki.etersoft.ru/Eterbackup
ETERBACKUP wiki page
